name: Deploy

on:
  push:
    branches:
      - main  # Запуск при каждом пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0 # GitHub Action, используемая для автоматического деплоя файлов на сервер через FTP
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/  # Локальная папка, которую нужно отправить
          server-dir: /public_html/  # Директория на сервере
          protocol: ftps # протокол для передачи файлов на сервер c использованием шифрования
